[FIX] mail_outbound_static: fix test py compat
Executing the unittests with a python version >= 3.7.4
causing following error.

Traceback (most recent call last):
  File "/opt/addons/mail_outbound_static/tests/test_ir_mail_server.py", line 117, in test_send_email_injects_from_with_canonical
    message = self._send_mail(mail_server_id=mail_server_id)
  File "/opt/addons/mail_outbound_static/tests/test_ir_mail_server.py", line 92, in _send_mail
    send_from, send_to, message_string = connect().sendmail.call_args[0]
TypeError: 'NoneType' object is not subscriptable

Now it checks the python version
and changes the call for higher versions